### ISSUE TITLE
请教如何用oc引导？

### ISSUE THREAD

**Issue by hahabaobei** [liaoyudong2/Dell-7070-mff-hackintosh#1]
我用小兵和远景的安装盘写入优盘。然后用DG删除旧的EFI文件，然后将你提供的EFI复制进去。
然后就没有然后了。
无法引导，是不是我少了步骤？麻烦指点下。目前是用OptiPlex-7060and7070-Catalina的EFI，Clover引导。可惜无法休眠。
非常感谢。

**Comment by liaoyudong2** [comment]
可能你需要启用一下showpicker=true参数和timeout=10 用于手动选择启动项 可以通过ctrl+enter进行默认启动项选择

**Comment by hahabaobei** [comment]
现在Clover引导ok。换OC没头绪。
进入mac OS之后，用Clover Configurator挂载硬盘的EFI，然后将Clover删除，复制OC文件夹进去。还需要做其他什么步骤？

**Comment by liaoyudong2** [comment]
主要是和引导项选择 如果是双系统的 就需要留意scan的权限数值 规避掉windows 因为我是单系统 所以引导项首选必然是mac的 我准备更新下oc引导

**Comment by hahabaobei** [comment]
我是单系统。只有1块SSD，安装的macOS。

**Comment by liaoyudong2** [comment]
但系统那肯定没有问题 你试试用安装前的EFI那个 看看你的启动项你所命名的启动盘符在第几个 选中后按ctrl+enter进行默认启动 后续就会自动按这个启动项启动了 如果出现启动到最后就突然重启的 那就需要你去解setup_var  我也放进去目录了的 当中包含了解dvmt和cfg lock

**Comment by liaoyudong2** [comment]
稳定版EFI已上传 三码自行替换了 showpicker和timeout选项可以自行打开 方便选择启动项 我默认是按照白果一样的启动的 包括开机声音也是可以了

**Comment by burugo** [comment]
请问这个efi支持hdmi接口的视频输出吗？

**Comment by burugo** [comment]
> 请问这个efi支持hdmi接口的视频输出吗？

用hackintool加了hdmi补丁终于可以了。。
