### ISSUE TITLE
大哥请问一下使用dp装转HDMI转接头可以不

### ISSUE THREAD

**Issue by chaseSpace** [liaoyudong2/Dell-7070-mff-hackintosh#12]
我准备买最新的7080mff，但是看到有些帖子说转接有毒，请问一下您了解吗

**Comment by chaseSpace** [comment]
另外一定要再买一个DW1560网卡吗，主板自带wifi网卡不行是吧？

**Comment by liaoyudong2** [comment]
@chaseSpace
DP转HDMI必须买芯片转HDMI的(这种本质是DP信号 通过外部芯片转HDMI信号) 不要买DP触发主机输出HDMI信号那种 (这种本质是HDMI信号)

自带Intel 9560的驱动我已经上传 config-intel-wifi.plist 改名config.plist 替换即可 自行测试是否OK

**Comment by chaseSpace** [comment]
老板送的转接头也不知道是哪一种，网卡知道了，谢谢！
