### ISSUE TITLE
请问成功进入 recovery 页面，可是 wired keyboard 都没有反应，是因为只接受 wired mouse input吗？

### ISSUE THREAD

**Issue by cyrusauyeungc** [liaoyudong2/Dell-7070-mff-hackintosh#14]
还是在 EFI / driver 上需要特殊照顾什么usb呢？
我的机型也是一样是 7070mff，只是 wifi 卡是 intel 9560 的，感谢。
![image](https://user-images.githubusercontent.com/69232468/103845330-d1eb1500-50d6-11eb-8a61-e410b1803a84.png)

**Comment by liaoyudong2** [comment]
![image](https://user-images.githubusercontent.com/7582071/103887225-ac352e80-511d-11eb-8f0d-794cf6d5da45.png)
可以用这三个驱动
地址:http://github.com/OpenIntelWireless/

**Comment by cyrusauyeungc** [comment]
你好，首先感谢你就算 close 了的issue 也有关注！
后来买了一只有线滑鼠后就成功进入 install 了，
==> 暂时还没能解决，后来的问题就是出现了 reboot loop

因为我的机型跟你的基本上是一样的，只是 wifi card 我还是用原本的 9560，
因此我就下载了 big sur ，可是不是20B29，只找到最新的20C69，搭配你 11.x 的EFI 使用

我的流程是用 mac 制作了usb drive，
EFI 分区就放了你的 11.x 的EFI，加上用了你准备好的 intel wifi 的 config.plist，
==》这里有疑问的是，plist 里面 type 只有 macmini8,1，其他的 serial/mlb/uuid 需要用 GenSMBIOS 补充吗？ 
==》 是不是 **不** 需要按照 opencore 的 guide 优化里面 plist的项目呢？

而 installer 分区就是按照 opencore 的installer制作方式，
下载 20C69 后制作的。

感谢你！

**Comment by liaoyudong2** [comment]
11.1我自己机器是已经安装过了的 看看晚点有空我更新一波上去吧 可以提供博通或者英特网卡的完成方案上去

**Comment by cyrusauyeungc** [comment]
感謝你！一直找解決方法都睡不著了，心裡想著因為基本上的硬件都一樣，不可能不成功的！

**Comment by cyrusauyeungc** [comment]
我估计另外一个问题就是 bios 的设定也需要关注的，
我有记忆需要修改的例如是disable secure boot， sata 改成 AHCI etc，
请问你有特别修改，还是都是restore factory setting 的bios 吗？感谢

**Comment by liaoyudong2** [comment]
> 感谢你！一直找解决方法都睡不着了，心里想着因为基本上的硬件都一样，不可能不成功的！

Intel网卡方案已经更新 可以自信测试引导 记得改名EFI-Intel为EFI目录

**Comment by liaoyudong2** [comment]
> 我估计另外一个问题就是 bios 的设定也需要关注的，
> 我有记忆需要修改的例如是disable secure boot， sata 改成 AHCI etc，
> 请问你有特别修改，还是都是restore factory setting 的bios 吗？感谢

其中没有什么特别设置的地方 你的键盘是否是2.4G的键盘 如果是蓝牙键盘之类的 肯定是不行的

**Comment by cyrusauyeungc** [comment]
我现在开始测试， bios 也先恢复原本的设置才开始，感谢你！
