### ISSUE TITLE
大佬 求一个耳麦一体的音频驱动

### ISSUE THREAD

**Issue by ningning21** [liaoyudong2/Dell-7070-mff-hackintosh#22]
如题··· 谢谢大佬

**Comment by magisk317** [comment]
同求同求啊，原来这个还跟驱动有关啊，我还以为我耳机不行呢。

**Comment by ningning21** [comment]
> 同求同求啊，原来这个还跟驱动有关啊，我还以为我耳机不行呢。

3.5的好像不行, 我用type c的耳麦一体可以

**Comment by liaoyudong2** [comment]
7070mff我去年就出掉咯.. 现在手上只有7080mff了.. 没法再修这些东西..
