### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by openaphid** [liaoyudong2/Dell-7070-mff-hackintosh#6]
I just want to express my appreciation for your great work, which helped me finish my build in half a day without messing around EFI files.

Is it by any chance you would upgrade it to support `10.15.5`?

**Comment by wqk317** [comment]
In fact, it is supported
![image](https://user-images.githubusercontent.com/13175615/85539023-01a96280-b648-11ea-80a3-e7a0d45f394c.png)

**Comment by openaphid** [comment]
Do you mean we can upgrade from 10.15.3 directly with the current EIF files? Is there a need to apply the framebuffer fix that's mentioned in [OpenCore document](https://dortania.github.io/OpenCore-Desktop-Guide/post-install/update.html#updating-macos)?

**Comment by openaphid** [comment]
I took the risk and upgraded my machine to 10.15.5 without any modification to EFI files. It works fine.
Thanks again.
